
-- CREATE
-- TEMPORARY TABLE popcsv (region_name VARCHAR, male_population INTEGER, female_population INTEGER, intersex_population INTEGER, total_population INTEGER, population_density DECIMAL );

-- DELETE FROM popcsv;

-- COPY popcsv
-- FROM '/home/sylvia/projects/covid_movement/region_pop.csv'
-- DELIMITER ','
-- CSV HEADER;

-- SELECT count(*) FROM popcsv;

-- INSERT INTO population_data( 
--     male_population,
--     female_population,
--     intersex_population,
--     total_population,
--     population_density,
--     region_id)
-- SELECT 
--     male_population,
--     female_population,
--     intersex_population,
--     total_population,
--     population_density,
--     region_id
-- FROM popcsv p
-- JOIN region r
-- ON UPPER(p.region_name)=UPPER(r.region_name);


-- DELETE FROM population_data;

-- ALTER TABLE population_data 
-- ALTER COLUMN population_data_id DROP IDENTITY IF EXISTS;

-- ALTER TABLE population_data
-- ADD CONSTRAINT population_data_pkey UNIQUE (population_data_id);

-- ALTER TABLE population_data 
-- ALTER COLUMN population_data_id ADD GENERATED BY DEFAULT AS IDENTITY;

-- ALTER TABLE population_data 
-- ALTER COLUMN population_data_id SET GENERATED BY DEFAULT;



-- DELETE FROM population_data;
SELECT * FROM population_data;
